# Dependabot configuration for WordPress QuickStart
# This file configures Dependabot to automatically check for updates
# to dependencies in both Composer (PHP) and npm (JavaScript) ecosystems.
#
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor Composer dependencies (PHP packages)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "rfair404"
    assignees:
      - "rfair404"
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
      - "composer"
    allow:
      # Allow updates for all dependency types
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore certain updates that might be too frequent or breaking
    ignore:
      # WordPress core: only update minor/patch versions automatically
      - dependency-name: "johnpbloch/wordpress-core"
        update-types: ["version-update:semver-major"]
    # Group related updates together to reduce PR noise
    groups:
      wordpress-core:
        patterns:
          - "johnpbloch/wordpress-*"
      coding-standards:
        patterns:
          - "*phpcs*"
          - "*coding-standards*"
          - "wp-coding-standards/*"
          - "automattic/vipwpcs"
          - "phpcompatibility/*"
          - "phpcsstandards/*"
          - "sirbrillig/phpcs-*"
      testing-framework:
        patterns:
          - "phpunit/*"
          - "yoast/phpunit-*"

  # Monitor npm dependencies (JavaScript packages)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "rfair404"
    assignees:
      - "rfair404"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "npm"
    allow:
      # Allow updates for all dependency types
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore certain updates that might cause compatibility issues
    ignore:
      # ESLint major versions can have breaking changes
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      # Playwright versions should be carefully tested
      - dependency-name: "@playwright/test"
        update-types: ["version-update:semver-major"]
    # Group related updates together
    groups:
      linting-tools:
        patterns:
          - "eslint*"
          - "prettier*"
          - "stylelint*"
          - "@typescript-eslint/*"
      testing-framework:
        patterns:
          - "@playwright/*"
          - "playwright*"
      build-tools:
        patterns:
          - "webpack*"
          - "babel*"
          - "@babel/*"

  # Monitor GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    reviewers:
      - "rfair404"
    assignees:
      - "rfair404"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    groups:
      setup-actions:
        patterns:
          - "actions/checkout"
          - "actions/setup-*"
          - "actions/cache"
      deployment-actions:
        patterns:
          - "actions/deploy-*"
          - "actions/upload-*"
          - "actions/download-*"